# Generated by Django 4.2.1 on 2023-05-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadigital', '0002_factura_mesa_pedido_usuario_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pedido',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificacion',
            field=models.CharField(default='bueno', max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(related_name='pedido_producto', to='cartadigital.producto'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='producto',
            field=models.ManyToManyField(related_name='carta_producto', to='cartadigital.producto'),
        ),
    ]
