# Generated by Django 4.2.1 on 2023-05-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadigital', '0003_remove_producto_pedido_calificacion_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
